name: Download and extract latest GSE release on Windows

on:
  workflow_call:
    # needed since it allows this to become a reusable workflow
  workflow_dispatch:
    # allows manual trigger

permissions:
  contents: "write"

jobs:
  download_and_extract:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download emu-win-release.7z
        uses: robinraju/release-downloader@v1.6
        with:
          repository: 'alex47exe/gse_fork'
          file-name: 'emu-win-release.7z'
          latest: true

      - name: Download emu-win-debug.7z
        uses: robinraju/release-downloader@v1.6
        with:
          repository: 'alex47exe/gse_fork'
          file-name: 'emu-win-debug.7z'
          latest: true

      - name: Install 7z
        run: choco install 7zip --no-progress

      - name: Extract emu-win-release.7z
        run: 7z x emu-win-release.7z -o./_gse_prerelease_win

      - name: Extract emu-win-debug.7z
        run: 7z x emu-win-debug.7z -o./_gse_prerelease_win